# Generated by Django 5.2.2 on 2025-06-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('PSQL', 'Postgres'), ('MSQL', 'Mysql'), ('SQLT', 'Sqlite'), ('MGDB', 'Mongodb')])),
                ('dump', models.TextField()),
            ],
        ),
    ]
