FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y wget gnupg lsb-release && \
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y postgresql-client-17 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY core/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app
ENV PYTHONPATH=/app/core

EXPOSE 8000

RUN ["python", "core/manage.py", "migrate"]
CMD ["python", "core/manage.py", "runserver", "0.0.0.0:8000"]