# Generated by Django 5.2.1 on 2025-06-27 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('schema_description', models.TextField()),
            ],
        ),
    ]
