# Generated by Django 5.2.1 on 2025-06-12 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('sql_dump', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='DBScheme',
        ),
        migrations.RemoveField(
            model_name='session',
            name='db_name',
        ),
        migrations.AddField(
            model_name='session',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 17, 17, 25, 236949)),
        ),
    ]
