# Generated by Django 5.2.1 on 2025-06-12 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_dbschema_delete_dbscheme_remove_session_db_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 17, 18, 6, 707841, tzinfo=datetime.timezone.utc)),
        ),
    ]
