# Generated by Django 5.2.1 on 2025-06-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_alter_session_last_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
