# Generated by Django 5.2.1 on 2025-06-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('ta', 'Teaching Assistant'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
